### ISSUE TITLE
Add .png sufix to the PNG icons

### ISSUE THREAD

**Issue by felipesanches** [Simple-BR/Br-Print3D#6]
There are tens of **PNG** icons in the **Icons/** directory that lack a proper filename extension. Please rename them so that their names end with **.png**

**Comment by lays147** [comment]
How asked before, I ask you to be patient because this project is very new and I'm having to make major changes to it. I will make the corrections in time.
Thanks!

**Comment by felipesanches** [comment]
Sure! No worries. Take your time. :-D I'm here to help, as well.
